### GET Menu
GET localhost:7071/api/GetMenu

### POST Order
POST localhost:7071/api/orders
Content-Type: application/json

{
  "CustomerId": "36CF7CA7-4BD2-4F67-B6C5-007FDCD12614",
  "Items": [
    {"MenuItemId": "1b10b09c-6b56-420a-8e79-f6b9be5fe20d", "Quantity": 1},
    {"MenuItemId": "7e1674e4-abba-4603-80a4-f10686278d7e", "Quantity": 2}
  ]
}

### POST ConfirmOrderDelivered
POST localhost:7071/api/orders/b8604f77-4d2c-4e2a-8708-5717b78f835d/confirm