### GET Menu
GET localhost:7272/api/GetMenu

### POST Order
POST localhost:7272/api/orders
Content-Type: application/json

{
  "CustomerId": "36CF7CA7-4BD2-4F67-B6C5-007FDCD12614",
  "Items": [
    {"MenuItemId": "5f4d8150-a72b-44e3-9c88-5cc7ed088c2d", "Quantity": 1},
    {"MenuItemId": "5199d3a3-ee0d-44f1-83b0-387dc38c46c6", "Quantity": 2}
  ]
}

### POST ConfirmOrderDelivered
POST localhost:7272/api/orders/b8604f77-4d2c-4e2a-8708-5717b78f835d/confirm